export const ADD_NOTE = 'ADD_NOTE'
export const UPDATE_NOTE = 'UPDATE_NOTE'
export const UPDATE_TITLE = 'UPDATE_TITLE'
export const ACTIVE_NOTE = 'ACTIVE_NOTE'
export const DELETE_NOTE = 'DELETE_NOTE'